### ISSUE TITLE
Use explicit `git add`

### ISSUE THREAD

**Issue by mikeshultz** [TankerHQ/tbump#35]
Instead of doing a `git add --update` for the entire working tree, just do the add on each file that `tbump` updated.  Or at least include a setting to turn off commits.

**Comment by dmerejkowsky** [comment]
Hum. Not sure I understand your use case here. 

`tbump` checks that the repo is clean before doing anything, precisely so that we only add files that changed. So using `git add --update` or add each file one by one should have exactly the same result. 

Unless you have files that are:
* changed by tbump 
* tracked by git
* and that you don't want to be in the bump commit

**Comment by mikeshultz** [comment]
Well, I don't really have a strong argument here as what I'm asking for is probably bad practice.  But a clean working tree isn't always desirable.  Thought maybe this would be a simple change to have tbump internally track what it updated and only add those files.  Alternatively, maybe a CLI arg to disable all git operations and just update the files.

None of this is really a big deal to me, so feel free to close this outright if you don't think it's a good fit for your project.  I can generally work around it with `git stash` when this situation comes up.

**Comment by dmerejkowsky** [comment]
Thanks for the clarification. I'll open a separate issue then.
