### ISSUE TITLE
tbump to determine new version by bumping single part

### ISSUE THREAD

**Issue by fizyk** [TankerHQ/tbump#73]
Could it be a desired feature for tbump to actually determine new version by itself? 

ie if the current_version would be `1.2.3` instead of calling

`tbump 1.2.4` one would call `tbump patch` ?

**Comment by dmerejkowsky** [comment]
Well, that's what `bumpversion` tried to do - turns out it's much harder than you might think - and it's why we started this project in the first place, with the explicit goal of keeping `bumpversion`'s good ideas, and not make the same mistakes.

So no, this feature will _not_ be implemented in this project, but thanks for asking anyway :)
